AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance in imported VPC/subnet with MongoDB installation

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

  AmiId:
    Type: String
    Default: ami-00beae93a2d981137

  RoleName:
    Type: String
    Default: WizEC2RolePlusS3AccessMongo

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 key pair
    Default: WizTechEC2KeyPair2026

# Resource Section
#
Resources:

  MongoENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue MySubnetPublic1Id
      PrivateIpAddress: 10.1.1.100
      GroupSet: 
        - !GetAtt MongoSecurityGroup.GroupId

  MongoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and MongoDB access
      VpcId: !ImportValue VPCA-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: mongodb-ec2-sg

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RoleName
      Path: /

  MongoEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2InstanceProfile
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MongoENI
          DeviceIndex: 0
      KeyName: !Ref  KeyName
      Tags:
        - Key: Name
          Value: MongoDB
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update packages
          dnf update -y || yum update -y

          # Create MongoDB repo file
          cat > /etc/yum.repos.d/mongodb-org-7.0.repo <<'EOF'
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc
          EOF

          # Install MongoDB
          sudo yum install -y mongodb-org-7.0.16 \
          mongodb-org-database-7.0.16 \
          mongodb-org-server-7.0.16 \
          mongodb-mongosh \
          mongodb-org-mongos-7.0.16 \
          mongodb-org-database-tools-extra-7.0.16

          # Enable and start mongod
          systemctl enable mongod
          systemctl start mongod

          # Allow remote connections
          sed -i 's/^  bindIp: .*/  bindIp: 0.0.0.0/' /etc/mongod.conf || true
          # Set mongodb accounts
          #
          #!/bin/bash
          set -euo pipefail

          MONGO_ADMIN_USER="admin"
          MONGO_ADMIN_PASS="12345678"
          FLASK_ADMIN_USER="flaskadmin"
          FLASK_ADMIN_PASS="12345678"
          # Start MongoDB (adjust if needed)
          systemctl start mongod || service mongod start

          # Wait for MongoDB
          until mongosh --quiet --eval 'db.runCommand({ ping: 1 })' >/dev/null 2>&1; do
            sleep 5
          done

          # Create admin user if not exists
          mongosh admin --quiet <<EOF
          if (db.getUser("${!MONGO_ADMIN_USER}") == null) {
            db.createUser({
              user: "${!MONGO_ADMIN_USER}",
              pwd: "${!MONGO_ADMIN_PASS}",
              roles: [ { role: "root", db: "admin" } ]
            });
            print("Admin user created");
          } else {
            print("Admin user already exists");
          }
          EOF

          # Create flaskadmin user if not exists
          mongosh admin --quiet <<EOF
          if (db.getUser("${!FLASK_ADMIN_USER}") == null) {
            db.createUser({
              user: "${!FLASK_ADMIN_USER}",
              pwd: "${!FLASK_ADMIN_PASS}",
              roles: [ { role: "readWrite", db: "wizns" } ]
            });
            print("Admin user created for wizns");
          } else {
            print("Admin user already exists");
          }
          EOF

          # Enable authentication if not already enabled
          if ! grep -q "authorization: enabled" /etc/mongod.conf; then
          cat <<EOF >> /etc/mongod.conf

          security:
            authorization: enabled
          EOF
          fi

          systemctl restart mongod
# Setup mongodb login/auth
#
# setup Crontab for daily backups
# crontab -e 0 2 * * * /usr/bin/python3 /home/ec2-user/mongodbscript.py

Outputs:
  InstanceId:
    Value: !Ref MongoEc2Instance

  PublicIp:
    Value: !GetAtt MongoEc2Instance.PublicIp

  PrivateIp:
    Value: !GetAtt MongoEc2Instance.PrivateIp

  SecurityGroupId:
    Value: !Ref MongoSecurityGroup